baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
enableEmoji = true

[params]
  background_image = '/Lambda-pattern.svg'
  content_background_image = '/Points-pattern.svg'

[menus]
  [[menus.main]]
    name = 'shx'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'about'
    pageRef = '/about'
    weight = 20

  [[menus.main]]
    name = 'jobs'
    pageRef = '/jobs'
    weight = 30

  [[menus.main]]
    name = 'blog'
    pageRef = '/posts'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
